branches:
  only:
    - 'master'

language: ruby
rvm:
  - 2.1.5

before_install:
  - gem install nokogiri -- --with-cflags='--std=gnu99'

script:
  - bundle exec rake db:setup
  - bundle exec rake test
